/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamo;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author hugo
 */
public class JPprestamo extends javax.swing.JPanel {

    Cconexion miCconexion = new Cconexion();
    JFrame JFPadre;
    private Jplista_libros milista;
    List<List<String>> resultado = new ArrayList<List<String>>();
    /**
     * Creates new form JPprestamo
     */
    public JPprestamo(JFrame padreJframe) {
        initComponents();
        JFPadre = padreJframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTnombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        JTautor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        JTeditorial = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        JpbtnBuscar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(26, 35, 126));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prestamo de libro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Parametros de busqueda");

        JTnombre.setBackground(jPanel1.getBackground());
        JTnombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTnombre.setForeground(new java.awt.Color(255, 255, 255));
        JTnombre.setText("Nombre");
        JTnombre.setBorder(null);
        JTnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTnombreMouseClicked(evt);
            }
        });
        JTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTnombreKeyReleased(evt);
            }
        });

        JTautor.setBackground(jPanel1.getBackground());
        JTautor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTautor.setForeground(new java.awt.Color(255, 255, 255));
        JTautor.setText("Autor");
        JTautor.setBorder(null);
        JTautor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTautorMouseClicked(evt);
            }
        });
        JTautor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTautorKeyReleased(evt);
            }
        });

        JTeditorial.setBackground(jPanel1.getBackground());
        JTeditorial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTeditorial.setForeground(new java.awt.Color(255, 255, 255));
        JTeditorial.setText("Editorial");
        JTeditorial.setBorder(null);
        JTeditorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTeditorialMouseClicked(evt);
            }
        });
        JTeditorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTeditorialKeyReleased(evt);
            }
        });

        JpbtnBuscar.setBackground(new java.awt.Color(26, 35, 126));
        JpbtnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JpbtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpbtnBuscarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar");

        javax.swing.GroupLayout JpbtnBuscarLayout = new javax.swing.GroupLayout(JpbtnBuscar);
        JpbtnBuscar.setLayout(JpbtnBuscarLayout);
        JpbtnBuscarLayout.setHorizontalGroup(
            JpbtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpbtnBuscarLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        JpbtnBuscarLayout.setVerticalGroup(
            JpbtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpbtnBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator3)
                                .addComponent(JTeditorial)
                                .addComponent(JTnombre))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JpbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTautor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTeditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(JpbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(664, 464));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Prestamo de libro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(576, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JpbtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpbtnBuscarMouseClicked
        // TODO add your handling code here:
        System.out.println("clickeado");
    }//GEN-LAST:event_JpbtnBuscarMouseClicked

    private void JTnombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTnombreMouseClicked
        this.JTnombre.setText("");
    }//GEN-LAST:event_JTnombreMouseClicked

    private void JTautorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTautorMouseClicked
        this.JTautor.setText("");
    }//GEN-LAST:event_JTautorMouseClicked

    private void JTeditorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTeditorialMouseClicked
        this.JTeditorial.setText("");
    }//GEN-LAST:event_JTeditorialMouseClicked

    private void JTnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTnombreKeyReleased
        
        //callable statement
        int numero = miCconexion.num_coin_buscar(this.JTnombre.getText(), 1);
        resultado = miCconexion.bucscarpornom(this.JTnombre.getText(), 0, 1);
        if(resultado.size() != 0)
        {
            List<String> arreglo = resultado.get(0);
        }
         //Poniendo nuevo panel en el formulario
        milista = new Jplista_libros(resultado, numero);
        milista.setSize(this.getSize());
        this.jPanel2.removeAll();
        this.jPanel2.add(milista);
        JFPadre.pack();
        this.jPanel2.revalidate();
        this.jPanel2.repaint();
        
    }//GEN-LAST:event_JTnombreKeyReleased

    private void JTautorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTautorKeyReleased
        int numero = miCconexion.num_coin_buscar(this.JTautor.getText(), 2);
        resultado = miCconexion.bucscarpornom(this.JTautor.getText(), 0, 2);
        if(resultado.size() != 0)
        {
            List<String> arreglo = resultado.get(0);
            System.out.println(arreglo.get(0));
        }
         //Poniendo nuevo panel en el formulario
        milista = new Jplista_libros(resultado, numero);
        milista.setSize(this.getSize());
        this.jPanel2.removeAll();
        this.jPanel2.add(milista);
        JFPadre.pack();
        this.jPanel2.revalidate();
        this.jPanel2.repaint();
    }//GEN-LAST:event_JTautorKeyReleased

    private void JTeditorialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTeditorialKeyReleased
        int numero = miCconexion.num_coin_buscar(this.JTeditorial.getText(), 3);
        resultado = miCconexion.bucscarpornom(this.JTeditorial.getText(), 0, 3);
        if(resultado.size() != 0)
        {
            List<String> arreglo = resultado.get(0);
            System.out.println(arreglo.get(0));
        }
         //Poniendo nuevo panel en el formulario
        milista = new Jplista_libros(resultado, numero);
        milista.setSize(this.getSize());
        this.jPanel2.removeAll();
        this.jPanel2.add(milista);
        JFPadre.pack();
        this.jPanel2.revalidate();
        this.jPanel2.repaint();
    }//GEN-LAST:event_JTeditorialKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTautor;
    private javax.swing.JTextField JTeditorial;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JPanel JpbtnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
