package usuario;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author FernandoJose
 */
public class crud_usuarios extends javax.swing.JFrame {
   
    modi_usu modificar = new modi_usu();
    public crud_usuarios() {
        initComponents();
        mostrar("");
    }
    
    private void mostrar(String palabra){
   try{     
   
//   ImageIcon icono=new ImageIcon(getClass().getResource("icon/add.png"));
//   btn_add.setIcon(icono);
   DefaultTableModel modelo= new DefaultTableModel();   
   modelo.addColumn("id");
   modelo.addColumn("Rol");
   modelo.addColumn("Nombre");
   modelo.addColumn("Apellido"); 
   modelo.addColumn("Contraseña");
   modelo.addColumn("Dirección");
   modelo.addColumn("Número");
   modelo.addColumn("Email");
   jTbl_usu.setModel(modelo);
   String sql="";
  if(palabra.equals("")){ 
  sql=" CALL PA_SelectUsuario() ";
  
  }
  else{ 
   sql="CALL PA_BuscarUsu('"+(palabra)+"')"; 
  } 
   
   String []array = new String[8];
   Connection con_usu = DriverManager.getConnection("jdbc:mysql://localhost:3307/biblioteca","root","");
   Statement st_usu = con_usu.createStatement();
   ResultSet rs_usu = st_usu.executeQuery(sql);
   //rs_usu=st_usu.executeQuery(sql);
        while(rs_usu.next())
        { 
        array[0]=rs_usu.getString(1);
        array[1]=rs_usu.getString(2);
        array[2]=rs_usu.getString(3);
        array[3]=rs_usu.getString(4);
        array[4]=rs_usu.getString(5);
        array[5]=rs_usu.getString(6);
        array[6]=rs_usu.getString(7);
        array[7]=rs_usu.getString(8);
        modelo.addRow(array);
        }
        jTbl_usu.setModel(modelo);
        con_usu.close(); 
    }                                          

    catch(Exception e){
     JOptionPane.showMessageDialog(null,("error "+e));
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jB_agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_usu = new javax.swing.JTable();
        busq_usu = new javax.swing.JTextField();
        jB_busq = new javax.swing.JButton();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB_agregar.setText("Agregar");
        jB_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_agregarActionPerformed(evt);
            }
        });

        jTbl_usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTbl_usu.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTbl_usu);

        jB_busq.setText("Buscar");
        jB_busq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_busqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_agregar)
                        .addGap(266, 266, 266)
                        .addComponent(busq_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jB_busq)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_agregar)
                    .addComponent(busq_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_busq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_busqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_busqActionPerformed
        // TODO add your handling code here:
        mostrar(busq_usu.getText());
    }//GEN-LAST:event_jB_busqActionPerformed

    private void jB_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_agregarActionPerformed
        // TODO add your handling code here:
        new Agregar_usu().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jB_agregarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       int filas=0;
       filas= this.jTbl_usu.getSelectedRow();
       if(filas>=0){
        modificar.setVisible(true);
        this.setVisible(false);
        modi_usu.aux.setText(jTbl_usu.getValueAt(filas,0).toString());
        modi_usu.jT_email.setText(jTbl_usu.getValueAt(filas,7).toString());
        modi_usu.jT_num.setText(jTbl_usu.getValueAt(filas,6).toString());
        modi_usu.jT_address.setText(jTbl_usu.getValueAt(filas,5).toString());
       }
        else{
        JOptionPane.showMessageDialog(null,"Seleccionar registro a modificar");
       }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void confirm(crud_usuarios confirm, int filas, String condicion){
        try{
            Connection con_usu = DriverManager.getConnection("jdbc:mysql://localhost:3307/biblioteca","root","");
            PreparedStatement pst_usu = con_usu.prepareStatement("CALL PA_DeleteUsu('"+condicion+"')");
        pst_usu.executeUpdate();
        con_usu.close();
        DefaultTableModel dtm = (DefaultTableModel) jTbl_usu.getModel(); //TableProducto es el nombre de mi tabla ;) 
        dtm.removeRow(filas);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error en: "+ex);
        }
        
    }
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        
        int filas= jTbl_usu.getSelectedRow();
      try{
      if(filas>=0){
        
        String condicion=jTbl_usu.getValueAt(filas,0).toString();
        
        new confirm_usu(this,filas,condicion).setVisible(true);
   
       }
       else{
        JOptionPane.showMessageDialog(null,"Seleccionar registro a eliminar");
       }
      }
      catch(Exception ex){
       JOptionPane.showMessageDialog(null,"Error en: "+ex);
      }
      
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crud_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crud_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crud_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crud_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crud_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busq_usu;
    private javax.swing.JButton jB_agregar;
    private javax.swing.JButton jB_busq;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTbl_usu;
    // End of variables declaration//GEN-END:variables
}
