/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author roberto
 */
public class form_update extends javax.swing.JFrame {

    /**
     * Creates new form form_update
     */
  Connection con;
  PreparedStatement pst;//query
  ResultSet rs=null;//rsultado
  Statement s;
  crud_libros open;
    
    public form_update() {
        initComponents();
        pivote.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        in_desc = new javax.swing.JTextField();
        in_anio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        in_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        in_cantidad = new javax.swing.JTextField();
        in_edicion = new javax.swing.JTextField();
        in_cod = new javax.swing.JTextField();
        in_observacion = new javax.swing.JTextField();
        pivote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(in_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 130, -1));
        getContentPane().add(in_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 170, 130, -1));

        jLabel3.setText("Descripción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel4.setText("cantidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel11.setText("Observación");
        jLabel11.setName("in_anio"); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel5.setText("Codigo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 251, 130, 30));

        jLabel6.setText("Edición");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        in_name.setName("in_namelib"); // NOI18N
        getContentPane().add(in_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 130, -1));

        jLabel2.setText("Nombre de libro");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel8.setText("Año ");
        jLabel8.setName("in_anio"); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        in_cantidad.setName("in_cantidad"); // NOI18N
        getContentPane().add(in_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, -1));

        in_edicion.setName("in_edicion"); // NOI18N
        getContentPane().add(in_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 140, 130, -1));

        in_cod.setName("in_cod"); // NOI18N
        getContentPane().add(in_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, -1));

        in_observacion.setName("in_observacion"); // NOI18N
        getContentPane().add(in_observacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 200, 130, 40));

        pivote.setName("pivote"); // NOI18N
        getContentPane().add(pivote, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            con=conexion_mysql.getConnection();
            
            String condicion=pivote.getText();

            pst=con.prepareStatement("update libros set lib_name=?, lib_descrip=?, lib_cantidad=?, lib_edicion=?, lib_year=?,lib_codigo=?, lib_observacion=? where id_lib ='"+condicion+"'");
            pst.setString(1,in_name.getText());
            pst.setString(2,in_desc.getText());
            pst.setInt(3,Integer.parseInt(in_cantidad.getText()));
            pst.setString(4,in_edicion.getText());
            pst.setInt(5,Integer.parseInt(in_anio.getText()));
            pst.setString(6,in_cod.getText());
            pst.setString(7,in_observacion.getText());
            pst.executeUpdate();
            con.close(); 
            open =new crud_libros();
            open.setVisible(true);
            this.setVisible(false);

        }
        catch(Exception ex){

            JOptionPane.showMessageDialog(null,("error"+ex));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField in_anio;
    public static javax.swing.JTextField in_cantidad;
    public static javax.swing.JTextField in_cod;
    public static javax.swing.JTextField in_desc;
    public static javax.swing.JTextField in_edicion;
    public static javax.swing.JTextField in_name;
    public static javax.swing.JTextField in_observacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel pivote;
    // End of variables declaration//GEN-END:variables
}
